const ActionTypes = {
  SET_API_TOKEN: 'SET_API_TOKEN',
  SET_CURRENCY: 'SET_CURRENCY',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_FILTER_POPUP: 'SET_FILTER_POPUP',
  SET_LAST_SEARCHES: 'SET_LAST_SEARCHES'
};

export default ActionTypes;
